language: node_js
node_js:
  - "0.12"
env:
  global:
    - NODE_ENV=test
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq uuid-dev
  - sudo apt-get install build-essential
  - npm install -g mocha
